#!/usr/bin/env bash
# Install nginx

sudo apt update
sudo apt install nginx -y

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html


echo "Holberton School" > /etc/nginx/html/index.html


printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
