#!/usr/bin/env bash
#Eroor page

sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
sudo touch /var/www/html/404-page.html

sudo echo "Holberton School" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404-page.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html;
        error_page 404 /404-page.html;

        server_name _;

        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
